version: "3"

services:

  mongo-database:
    image: mongo:6
    container_name: "mongo_database"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin123
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - "./mongodata:/data/database"
    networks:
      - development-network

  postgres-database:
    container_name: "postgres_database"
    image: postgres
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
    volumes:
      - "./postgresdata:/data/postgres"
    ports:
      - "5432:5432"
    networks:
      - development-network
    restart: always

networks:
  development-network:
    name: development-network